qdrant:
  networkPolicy:
    allowFromWorkloads:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: unicorn
        podSelector:
          matchLabels:
            app.kubernetes.io/name: unicorn
