{{- if .Values.grafana.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "unicorn-tooling.grafanaFullname" . }}
  labels:
    {{- include "unicorn-tooling.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
type: Opaque
stringData:
  admin-user: {{ .Values.grafana.adminUser | quote }}
  admin-password: {{ .Values.grafana.adminPassword | quote }}
{{- end }}
